### ISSUE TITLE
大佬，启动报错

### ISSUE THREAD

**Issue by 397688551** [taishan666/tarzan-navigation#1]
![image](https://github.com/taishan666/tarzan-navigation/assets/37072662/149c3b75-1cba-427e-a5d9-ffe2efb33ac0)
org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "create table biz_category (id integer generated by default as identity, create_time timestamp, update_time timestamp, description varchar(255), icon varchar(255), name varchar(255), pid integer, sort integer, status integer, type integer, primary key (id))" via JDBC Statement
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:67)
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.applySqlString(AbstractSchemaMigrator.java:559)
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.applySqlStrings(AbstractSchemaMigrator.java:504)
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.createTable(AbstractSchemaMigrator.java:277)
	at org.hibernate.tool.schema.internal.GroupedSchemaMigratorImpl.performTablesMigration(GroupedSchemaMigratorImpl.java:71)
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.performMigration(AbstractSchemaMigrator.java:207)
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.doMigration(AbstractSchemaMigrator.java:114)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:184)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:73)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:316)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:469)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1259)

**Comment by 397688551** [comment]
解决了，将@GeneratedValue(strategy = GenerationType.IDENTITY)改为@GeneratedValue(strategy = GenerationType.AUTO)
